services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Devsk\DsNotifier\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Attribute/*'
      - '../Classes/Event/*'
      - '../Classes/Domain/Model/*'

  Devsk\DsNotifier\EventListener\NotifierListener:
    tags:
      - name: event.listener

  Devsk\DsNotifier\EventListener\Typo3\Core\Cache\CacheFlushListener:
    tags:
      - name: event.listener

  Devsk\DsNotifier\EventListener\Typo3\Core\Cache\CacheWarmupListener:
    tags:
      - name: event.listener

  Devsk\DsNotifier\Command\CustomCommand:
    tags:
      - name: 'console.command'
        command: 'notifier:custom'
        description: 'Testing custom command'
